'use client';

import React from 'react';
import { NavItemKey } from '@/types';
import { SectionHeader } from '@/components/dashboard/SectionHeader';
import { StatusBadge } from '@/components/ui/StatusBadge';
import { ArrowLeft, Sparkles, Layers, ShieldCheck, Terminal, ExternalLink } from 'lucide-react';

interface PlaceholderModuleViewProps {
  tabKey: NavItemKey;
  onBackToCommandCenter: () => void;
  onDeployAgent: () => void;
}

const MODULE_DETAILS: Record<NavItemKey, { title: string; category: string; description: string; telemetry: string }> = {
  'command-center': { title: 'Command Center', category: 'Core', description: 'Central executive cockpit.', telemetry: 'All nodes synchronized' },
  'research-workspace': { title: 'Research Workspace', category: 'Workspace', description: 'Deep quantitative financial modeling and multi-source filing aggregation.', telemetry: 'Indexing SEC EDGAR, Bloomberg feeds & CapIQ' },
  'portfolio-allocation': { title: 'Portfolio Allocation', category: 'Capital Engine', description: 'Risk-parity rebalancing, factor tilt analysis, and cash deployment modeling.', telemetry: 'Continuous Monte Carlo parameter updates' },
  'agent-marketplace': { title: 'Agent Marketplace', category: 'Intelligence', description: 'Autonomous financial intelligence agents on escrow rail.', telemetry: '3 agents available' },
  'public-markets': { title: 'Public Markets', category: 'Investments', description: 'Global equities, ETF tracking, earnings surprise analysis, and beta monitoring.', telemetry: 'NYSE, NASDAQ & LSE feeds live' },
  'private-markets': { title: 'Private Markets', category: 'Investments', description: 'Secondary direct transactions, GP stake valuations, and fund performance records.', telemetry: '18 active private portfolio marks' },
  'deal-pipeline': { title: 'Deal Pipeline', category: 'Investments', description: 'Venture & growth stage pipelines with committee scoring and milestone logs.', telemetry: '6 active opportunities in diligence' },
  'watchlist': { title: 'Watchlist', category: 'Investments', description: 'Monitored strategic candidates across autonomous hardware and defense tech.', telemetry: '14 companies tracked' },
  'research': { title: 'Research Hub', category: 'Intelligence', description: 'Institutional equity research, thematic whitepapers, and macro forecasts.', telemetry: '42 published institutional memos' },
  'valuations': { title: 'Valuations Engine', category: 'Intelligence', description: 'Discounted cash flow, trading multiples, and synthetic private marks.', telemetry: 'Q2 2026 mark-to-model benchmarked' },
  'risk': { title: 'Risk & Stress Testing', category: 'Intelligence', description: 'Value at Risk (VaR), geopolitical bottleneck mapping, and liquidity runway.', telemetry: 'SOX -15% stress simulation computed' },
  'due-diligence': { title: 'Due Diligence Data Rooms', category: 'Intelligence', description: 'Virtual data room ingestion, cap table audit, and IP verification.', telemetry: '2 active diligence rooms' },
  'investment-memos': { title: 'Investment Memos', category: 'Intelligence', description: 'Evidence-backed memos generated by Faro and specialist agents.', telemetry: '8 IC-approved investment memos' },
  'tasks': { title: 'Task Queue', category: 'Operations', description: 'Operational workflows, IC voting schedules, and capital call authorizations.', telemetry: '5 open action items' },
  'work-orders': { title: 'Work Orders', category: 'Operations', description: 'All agent delegations, escrow locks, and delivery acceptances.', telemetry: '3 active delegation contracts' },
  'agent-activity': { title: 'Agent Activity Telemetry', category: 'Operations', description: 'Real-time compute logs, token telemetry, and verification audit trail.', telemetry: 'Zero-knowledge verification verified' },
  'documents': { title: 'Document Vault', category: 'Operations', description: 'LP agreements, SAFEs, convertible notes, and compliance records.', telemetry: 'Encrypted institutional vault' },
  'settings': { title: 'Platform Settings', category: 'Configuration', description: 'Fund parameters, API integrations, custodian keys, and team roles.', telemetry: 'Single Sign-On (SSO) active' },
  'data-health': { title: 'Data Health', category: 'Configuration', description: 'Manage financial data integrations and sync status.', telemetry: 'System nominal' },
  'help': { title: 'Help & Knowledge Base', category: 'Support', description: 'Platform documentation, agent API SDKs, and institutional support desk.', telemetry: 'SLA: Priority < 15 mins' },
  'agent-orchestrator': { title: 'Faro Orchestrator', category: 'Intelligence', description: 'Multi-agent workflow coordination with dependency resolution and approval gates.', telemetry: 'Orchestrating 4 agent types' },
  'agent-economy': { title: 'Agent Economy', category: 'Intelligence', description: 'Marketplace analytics, reputation scores, and decentralized agent activity.', telemetry: '3 active agent providers' }
};

export const PlaceholderModuleView: React.FC<PlaceholderModuleViewProps> = ({
  tabKey,
  onBackToCommandCenter,
  onDeployAgent
}) => {
  const details = MODULE_DETAILS[tabKey] || {
    title: 'Module',
    category: 'Institutional OS',
    description: 'Autonomous financial module.',
    telemetry: 'Active'
  };

  return (
    <div className="space-y-6 pb-12 max-w-6xl mx-auto animate-in fade-in duration-150">
      {/* Back button */}
      <button
        onClick={onBackToCommandCenter}
        className="inline-flex items-center gap-1.5 text-xs text-[#6C726F] hover:text-[#18191B] font-medium transition-colors cursor-pointer"
      >
        <ArrowLeft className="w-3.5 h-3.5" />
        <span>Return to Capital Command Center</span>
      </button>

      <SectionHeader
        kicker={details.category}
        title={details.title}
        subtitle={details.description}
        badge={
          <StatusBadge variant="sage" size="xs" dot>
            {details.telemetry}
          </StatusBadge>
        }
      />

      {/* Institutional Module Card */}
      <div className="bg-white border border-[#EDEDEB] rounded-lg p-8 shadow-2xs space-y-6 text-center max-w-2xl mx-auto mt-8">
        <div className="w-12 h-12 rounded-xl bg-[#EBF5F1] text-[#245241] flex items-center justify-center mx-auto">
          <Sparkles className="w-6 h-6 text-[#87BAA4]" />
        </div>

        <div>
          <h3 className="text-lg font-bold text-[#141618]">
            {details.title} Module
          </h3>
          <p className="text-xs text-[#6C726F] mt-1 max-w-md mx-auto leading-relaxed">
            This module is connected to the Faro institutional data bus. Real-time telemetry is streaming from your custody and broker accounts.
          </p>
        </div>

        <div className="flex flex-wrap items-center justify-center gap-3 pt-2">
          <button
            onClick={onBackToCommandCenter}
            className="px-4 py-2 rounded-md bg-[#141618] text-white text-xs font-semibold hover:bg-neutral-800 transition-colors shadow-2xs cursor-pointer"
          >
            Go to Command Center
          </button>
          <button
            onClick={onDeployAgent}
            className="px-4 py-2 rounded-md border border-[#EDEDEB] hover:bg-[#F5F4F5] text-xs font-semibold text-[#18191B] transition-colors cursor-pointer"
          >
            Assign Agent to this Module
          </button>
        </div>
      </div>
    </div>
  );
};
